### ISSUE TITLE
Message «PLG_SYSTEM_JTALDEF_DISABLED_BY» displayed on websites other than German 

### ISSUE THREAD

**Issue by crimle** [JoomTools/plg_system_jtaldef#13]
This issue is related to 
- Websites with default language other than «German» or 
- Multilingual websites where the user selects a language other than «German»

In the left top corner there is a message
PLG_SYSTEM_JTALDEF_DISABLED_BY 
being displayed. Screenshot:

<img width="800" alt="PLG_SYSTEM_JTALDEF_DISABLED_BY" src="https://user-images.githubusercontent.com/51155809/226845735-7b92ab84-812c-42c5-8422-53786bdb1d4e.png">

**Comment by degobbis** [comment]
I could not reproduce the bug with the Joomla Core Multilanguage sample installation. 
Since I include `en-GB` and that is the default fallback language, this placeholder should always be loaded and used.

However, while trying to reproduce your bug, I noticed others that may fix yours as well.

Can you please test and report this version here? 
[plg_system_jtaldef-2.0.8-dev.zip](https://github.com/joomtools/plg_system_jtaldef/files/11038864/plg_system_jtaldef-2.0.8-dev.zip)

**Comment by crimle** [comment]
I am happy to confirm, that plg_system_jtaldef-2.0.8-dev.zip resolves this issue.

**Comment by degobbis** [comment]
Thx for reporting
