### ISSUE TITLE
fontawesome not loaded

### ISSUE THREAD

**Issue by pklinke** [JoomTools/plg_system_jtaldef#18]
Hi,

I have one site where fontawesome is not loaded. In header I see this line: <link rel="stylesheet" href="/fonts/css/all.css" data-jtaldef-processed="2.0.11"> but now icon is shown. Plugin is loaded at last position.

Because of the site is not public now, I can't add the url and login here. Hope you can help again like three years ago.

Peter

**Comment by pklinke** [comment]
Added js script with no change:

**Comment by degobbis** [comment]
Hello Peter,
I don't know what to say about this. I thought that if you opened a new issue, the stored template for bug reports would be displayed. Perhaps I can say more if you answer the following questions in as much detail as possible:

**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Which version is used:**
 - Plugin version: 
 - Joomla version:
 - FontAwesome version:
 - PHP version:

**How is FontAwesome integrated:**
FontAwesome currently only supports embedding from the original site (even Pro), but not CDNs.

**Screenshots**
- Plugin configuration:
- Browser developer toolbar (the `<head>...</head>` block):
- The problem part on site, with and without the active plugin:

**Additional context**
Add any other context about the problem here.

**Comment by degobbis** [comment]
Closed because no feedback has been received for a month.
